# Emits the resource script that goes into the launcher EXE: the unlocker DLL and
# the default config as embedded payloads, plus the control window's layout.
#
# Invoked from CMakeLists.txt via `cmake -P` with:
#   -DOUT=<generated .rc path>  -DDLL=<mw2_unlocker.dll path>  -DINI=<unlocker.ini path>
#
# The numeric ids below MUST stay in sync:
#   101 = the unlocker DLL        (launcher/main.cpp, kResourceDll)
#   102 = the default config      (launcher/main.cpp, kResourceIni)
#   103 = the control dialog      (launcher/gui.cpp,   kDialogMain)
#  1001..1020 = its controls      (launcher/gui.cpp,   kId*)
#
# The layout is here rather than built with CreateWindowEx calls because a dialog
# template gives the right font, tab order and focus handling for free. The
# colours are not: every control that would draw itself in system colours is
# owner-drawn in gui.cpp, and the two sliders plus the hotkey box are custom
# controls of the launcher's own, because the stock trackbar cannot be recoloured
# at all. The window itself paints the four cards it is divided into.

if(NOT OUT OR NOT DLL OR NOT INI)
    message(FATAL_ERROR "generate_rc.cmake requires -DOUT, -DDLL and -DINI")
endif()

if(NOT EXISTS "${DLL}")
    message(FATAL_ERROR "generate_rc.cmake: DLL not found: ${DLL}")
endif()

if(NOT EXISTS "${INI}")
    message(FATAL_ERROR "generate_rc.cmake: config not found: ${INI}")
endif()

file(TO_NATIVE_PATH "${DLL}" dll_native)
file(TO_NATIVE_PATH "${INI}" ini_native)

file(WRITE "${OUT}"
"// Generated by launcher/generate_rc.cmake - do not edit.
// Payload embedded into MW2Unlocker.exe, plus the control window layout.

#include <windows.h>

101 RCDATA \"${dll_native}\"
102 RCDATA \"${ini_native}\"

103 DIALOGEX 0, 0, 300, 338
STYLE DS_SETFONT | DS_MODALFRAME | DS_FIXEDSYS | DS_CENTER | WS_POPUP | WS_CAPTION | WS_SYSMENU
CAPTION \"MW2 Unlocker\"
FONT 9, \"MS Shell Dlg\", 400, 0, 0x1
BEGIN
    LTEXT           \"Frame rate cap\", 1013, 20, 26, 120, 11
    EDITTEXT        1003, 234, 24, 46, 14, ES_AUTOHSCROLL | ES_NUMBER
    LTEXT           \"0 is uncapped.\", -1, 20, 40, 220, 9
    CONTROL         \"\", 1002, \"MW2Slider\", WS_TABSTOP, 20, 51, 260, 14
    CONTROL         \"Cap the frame rate\", 1001, \"Button\", BS_OWNERDRAW | WS_TABSTOP, 20, 70, 170, 11

    LTEXT           \"Field of view\", 1014, 20, 100, 120, 11
    EDITTEXT        1006, 234, 98, 46, 14, ES_AUTOHSCROLL
    LTEXT           \"Degrees. Tick the box below for a wider view than 80.\", -1, 20, 114, 230, 9
    CONTROL         \"\", 1005, \"MW2Slider\", WS_TABSTOP, 20, 125, 260, 14
    CONTROL         \"Change the field of view\", 1004, \"Button\", BS_OWNERDRAW | WS_TABSTOP, 20, 144, 170, 11
    CONTROL         \"Raise the engine's 80-degree clamp\", 1007, \"Button\", BS_OWNERDRAW | WS_TABSTOP, 20, 158, 230, 11

    LTEXT           \"Mouse sensitivity\", 1017, 20, 194, 140, 11
    EDITTEXT        1020, 234, 192, 46, 14, ES_AUTOHSCROLL
    CONTROL         \"\", 1019, \"MW2Slider\", WS_TABSTOP, 20, 205, 260, 14
    CONTROL         \"Change the mouse sensitivity\", 1018, \"Button\", BS_OWNERDRAW | WS_TABSTOP, 20, 224, 200, 11

    LTEXT           \"Toggle key\", 1015, 20, 257, 120, 11
    CONTROL         \"\", 1016, \"MW2KeyBox\", WS_TABSTOP, 236, 254, 44, 15
    LTEXT           \"Click the key to step through F1-F12.\", -1, 20, 270, 200, 9

    LTEXT           \"\", 1011, 12, 292, 276, 18

    CONTROL         \"Apply & save\", 1012, \"Button\", BS_OWNERDRAW | BS_DEFPUSHBUTTON | WS_TABSTOP, 132, 314, 78, 16
    CONTROL         \"Close\", IDCANCEL, \"Button\", BS_OWNERDRAW | WS_TABSTOP, 216, 314, 74, 16
END
")
