# Emits the resource script that embeds the unlocker DLL and the default config
# into the launcher EXE, so the launcher ships as a single self-contained file.
#
# Invoked from CMakeLists.txt via `cmake -P` with:
#   -DOUT=<generated .rc path>  -DDLL=<mw2_unlocker.dll path>  -DINI=<unlocker.ini path>
#
# The numeric ids below MUST stay in sync with launcher/main.cpp:
#   101 = the unlocker DLL      102 = the default config

if(NOT OUT OR NOT DLL OR NOT INI)
    message(FATAL_ERROR "generate_rc.cmake requires -DOUT, -DDLL and -DINI")
endif()

if(NOT EXISTS "${DLL}")
    message(FATAL_ERROR "generate_rc.cmake: DLL not found: ${DLL}")
endif()

if(NOT EXISTS "${INI}")
    message(FATAL_ERROR "generate_rc.cmake: config not found: ${INI}")
endif()

file(TO_NATIVE_PATH "${DLL}" dll_native)
file(TO_NATIVE_PATH "${INI}" ini_native)

file(WRITE "${OUT}"
"// Generated by launcher/generate_rc.cmake - do not edit.
// Payload embedded into MW2Unlocker.exe.
101 RCDATA \"${dll_native}\"
102 RCDATA \"${ini_native}\"
")
